<?php

namespace App\Services;

use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;

class CulqiService
{
    protected $publicKey;
    protected $privateKey;
    protected $baseUrl = 'https://api.culqi.com/v2';

    public function __construct()
    {
        $this->publicKey = env('CULQI_PUBLIC_KEY');
        $this->privateKey = env('CULQI_PRIVATE_KEY');
    }

    /**
     * Create a charge using a token generated by Culqi Checkout
     *
     * @param string $token
     * @param int $amount Amount in integer format (e.g., 100.00 = 10000)
     * @param string $email Customer email
     * @param string $orderId Internal Order ID for reference
     * @return array
     */
    public function createCharge($token, $amount, $email, $orderId)
    {
        try {
            $response = Http::withToken($this->privateKey, 'Bearer')
                ->withHeaders([
                    'Accept' => 'application/json',
                    'Content-Type' => 'application/json',
                ])
                ->post("{$this->baseUrl}/charges", [
                    'amount' => $amount,
                    'currency_code' => 'PEN',
                    'email' => $email,
                    'source_id' => $token,
                    'description' => "Pedido #{$orderId} en RepuestoFijo",
                    'antifraud_details' => [
                        'first_name' => explode('@', $email)[0],
                        'last_name' => 'Cliente',
                        'email' => $email,
                        'phone_number' => '999999999',
                        'device_fingerprint' => 'web-checkout'
                    ],
                    'metadata' => [
                        'pedido_id' => $orderId
                    ]
                ]);

            if ($response->successful()) {
                return [
                    'success' => true,
                    'charge' => $response->json(),
                ];
            }

            Log::error('Culqi Charge Error', ['response' => $response->json()]);

            $errorData = $response->json();
            return [
                'success' => false,
                'message' => $errorData['user_message'] ?? 'Hubo un error procesando el pago con Culqi.',
                'error' => $errorData,
            ];

        } catch (\Exception $e) {
            Log::error('Culqi Service Exception', ['message' => $e->getMessage()]);
            return [
                'success' => false,
                'message' => 'Error de conexión con la pasarela de pagos. Por favor, intenta de nuevo.',
            ];
        }
    }
}
